# Generated by Django 3.0.2 on 2020-01-11 21:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('carauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagassignment',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 0, 0, tzinfo=utc)),
        ),
    ]
