# Generated by Django 3.0.2 on 2020-01-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carauth', '0002_auto_20200111_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='tag',
        ),
        migrations.AddField(
            model_name='login',
            name='tag_uid',
            field=models.CharField(default='00', max_length=20),
            preserve_default=False,
        ),
    ]
