# Generated by Django 3.0.2 on 2020-01-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carauth', '0003_auto_20200112_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='uid',
            field=models.CharField(default='00', max_length=20),
        ),
    ]
