# Generated by Django 2.2.7 on 2020-02-02 21:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('carauth', '0005_unregistredtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arduino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arduino_mac', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='locationhistory',
            old_name='datetime',
            new_name='datetime_field',
        ),
        migrations.CreateModel(
            name='ArduinoAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 0, 0, tzinfo=utc))),
                ('arduino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carauth.Arduino')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carauth.Car')),
            ],
        ),
    ]
