# Generated by Django 2.2.7 on 2020-03-02 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carauth', '0006_auto_20200202_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='tag_uid',
        ),
        migrations.AddField(
            model_name='login',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carauth.Tag'),
        ),
    ]
