# Generated by Django 2.2.7 on 2020-03-02 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carauth', '0007_auto_20200302_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carauth.Tag'),
        ),
    ]
