# Generated by Django 2.2.7 on 2020-03-06 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carauth', '0008_auto_20200302_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='arduino_session',
        ),
        migrations.RemoveField(
            model_name='login',
            name='location',
        ),
        migrations.AddField(
            model_name='login',
            name='arduino',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='carauth.Arduino'),
            preserve_default=False,
        ),
    ]
