# Generated by Django 2.2.7 on 2020-03-14 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carauth', '0009_auto_20200306_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationhistory',
            name='arduino',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='carauth.Arduino'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locationhistory',
            name='login',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carauth.Login'),
        ),
        migrations.AlterField(
            model_name='login',
            name='arduino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carauth.Arduino'),
        ),
    ]
